kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-timeout-intermediary
  namespace: test-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-timeout-intermediary
      version: v1
  template:
    metadata:
      labels:
        app: demo-timeout-intermediary
        version: v1
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: demo-timeout-intermediary
          image: 'evil26r/demo_timeout_intermediary:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: intermediary.base.url
              value: 'http://demo-timeout-endpoint.test-project.svc.cluster.local/'
            - name: endpoint.host
              value: demo-timeout-endpoint
