kind: Deployment
apiVersion: apps/v1
metadata:
  name: demo-timeout-intermediary
  namespace: test-project
  annotations:
    deployment.kubernetes.io/revision: '13'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-timeout-intermediary
  template:
    metadata:
      labels:
        app: demo-timeout-intermediary
      annotations:
        sidecar.istio.io/inject: 'true'
    spec:
      containers:
        - name: demo-timeout-intermediary
          image: evil26r/demo_timeout_intermediary
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: intermediary.base.url
              value: 'http://demo-timeout-endpoint.test-project.svc.cluster.local/'
            - name: endpoint.host
              value: demo-timeout-endpoint.test-project.svc.cluster.local
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
