apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: demo-timeout-endpoint
  namespace: test-project
spec:
  hosts:
    - demo-timeout-endpoint
  http:
    - fault:
        delay:
          fixedDelay: 2s
          persent: 100
      route:
        - destination:
            host: demo-timeout-endpoint