server:
  port: 8080
  ssl:
    key-store-type: JKS
    key-store: D:\key\istio_mtls\keystore.jks
    key-store-password: 123456
    key-alias: localhost
    enabled: true
    trust-store-password: 123456
    trust-store: D:\key\istio_mtls\keystore.jks
    client-auth: need